namespace RagBook.Modules.Chat;

/// <summary>
/// Configuration for keyless generation through the local <c>claude</c> CLI (US-22). Off by default. When enabled,
/// a chat ask with no usable API key is generated by shelling out to the installed, already-authenticated CLI
/// instead of the Anthropic HTTP API. Config-driven — no magic values (§V/§VII). The CLI must be present + logged in
/// on the machine running the API (local <c>dotnet run</c> / Aspire, or a self-host image that ships it).
/// </summary>
public sealed class ClaudeCliOptions
{
    /// <summary>Configuration section name.</summary>
    public const string SectionName = "ClaudeCli";

    /// <summary>Whether keyless CLI generation is enabled (fallback used only when no key is available).</summary>
    public bool Enabled { get; set; }

    /// <summary>The CLI executable (on PATH or an absolute path).</summary>
    public string Command { get; set; } = "claude";

    /// <summary>Optional model alias/name passed to the CLI (<c>--model</c>); null uses the CLI's default.</summary>
    public string? Model { get; set; }

    /// <summary>Maximum seconds to wait for the CLI to produce an answer before treating it as unavailable.</summary>
    public int TimeoutSeconds { get; set; } = 120;
}
